using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;

namespace SmartClinic.Model
{
    public enum States
    {
        [Description("")]
        noSelection,
        [Description("AL")]
        AL,
        [Description("AK")]
        AK,
        [Description("AR")]
        AR,
        [Description("AZ")]
        AZ,
        [Description("CA")]
        CA,
        [Description("CO")]
        CO,
        [Description("CT")]
        CT,
        [Description("D.C.")]
        DC,
        [Description("DE")]
        DE,
        [Description("FL")]
        FL,
        [Description("GA")]
        GA,
        [Description("HI")]
        HI,
        [Description("TA")]
        IA,
        [Description("ID")]
        ID,
        [Description("IL")]
        IL,
        [Description("IN")]
        IN,
        [Description("KS")]
        KS,
        [Description("KY")]
        KY,
        [Description("LA")]
        LA,
        [Description("MA")]
        MA,
        [Description("MD")]
        MD,
        [Description("ME")]
        ME,
        [Description("MI")]
        MI,
        [Description("MN")]
        MN,
        [Description("MO")]
        MO,
        [Description("MS")]
        MS,
        [Description("MT")]
        MT,
        [Description("NC")]
        NC,
        [Description("ND")]
        ND,
        [Description("NE")]
        NE,
        [Description("NH")]
        NH,
        [Description("NJ")]
        NJ,
        [Description("NM")]
        NM,
        [Description("NV")]
        NV,
        [Description("NY")]
        NY,
        [Description("OK")]
        OK,
        [Description("OH")]
        OH,
        [Description("OR")]
        OR,
        [Description("PA")]
        PA,
        [Description("RI")]
        RI,
        [Description("SC")]
        SC,
        [Description("SD")]
        SD,
        [Description("TN")]
        TN,
        [Description("TX")]
        TX,
        [Description("UT")]
        UT,
        [Description("VA")]
        VA,
        [Description("VT")]
        VT,
        [Description("WA")]
        WA,
        [Description("WI")]
        WI,
        [Description("WV")]
        WV,
        [Description("WY")]
        WY
    }
}
