-- MySQL Script generated by MySQL Workbench
-- Thu Oct  1 19:35:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema clinic_management
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `clinic_management` ;

-- -----------------------------------------------------
-- Schema clinic_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinic_management` DEFAULT CHARACTER SET utf8 ;
USE `clinic_management` ;

-- -----------------------------------------------------
-- Table `clinic_management`.`administrators`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinic_management`.`administrators` ;

CREATE TABLE IF NOT EXISTS `clinic_management`.`administrators` (
  `administrator_id` VARCHAR(25) NOT NULL,
  `personal_information_id` INT UNSIGNED NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`administrator_id`),
  INDEX `administrators_personal_information_id_idx` (`personal_information_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `administrator_id_UNIQUE` (`administrator_id` ASC),
  CONSTRAINT `administrators_personal_information_id`
    FOREIGN KEY (`personal_information_id`)
    REFERENCES `clinic_management`.`personal_information` (`personal_information_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinic_management`.`appointments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinic_management`.`appointments` ;

CREATE TABLE IF NOT EXISTS `clinic_management`.`appointments` (
  `patient_id` VARCHAR(25) NOT NULL,
  `date` DATETIME NOT NULL,
  `doctor_id` VARCHAR(25) NOT NULL,
  `reason` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`patient_id`, `date`),
  INDEX `appointments_doctors_id_idx` (`doctor_id` ASC),
  CONSTRAINT `appointments_patients_id`
    FOREIGN KEY (`patient_id`)
    REFERENCES `clinic_management`.`patients` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `appointments_doctors_id`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `clinic_management`.`doctors` (`doctor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinic_management`.`doctors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinic_management`.`doctors` ;

CREATE TABLE IF NOT EXISTS `clinic_management`.`doctors` (
  `doctor_id` VARCHAR(25) NOT NULL,
  `personal_information_id` INT UNSIGNED NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`doctor_id`),
  INDEX `doctors_personal_information_id_idx` (`personal_information_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `doctor_id_UNIQUE` (`doctor_id` ASC),
  CONSTRAINT `doctors_personal_information_id`
    FOREIGN KEY (`personal_information_id`)
    REFERENCES `clinic_management`.`personal_information` (`personal_information_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinic_management`.`doctor_specialties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinic_management`.`doctor_specialties` ;

CREATE TABLE IF NOT EXISTS `clinic_management`.`doctor_specialties` (
  `doctor_id` VARCHAR(25) NOT NULL,
  `specialty` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`doctor_id`, `specialty`),
  CONSTRAINT `specialties_doctor_id`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `clinic_management`.`doctors` (`doctor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinic_management`.`lab_test_results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinic_management`.`lab_test_results` ;

CREATE TABLE IF NOT EXISTS `clinic_management`.`lab_test_results` (
  `patient_id` VARCHAR(25) NOT NULL,
  `appointment_date` DATETIME NOT NULL,
  `lab_test_code` VARCHAR(45) NOT NULL,
  `lab_test_date` DATETIME NOT NULL,
  `result` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`patient_id`, `appointment_date`, `lab_test_code`),
  INDEX `lab_test_results_code_idx` (`lab_test_code` ASC),
  CONSTRAINT `lab_test_results_visits_id`
    FOREIGN KEY (`patient_id` , `appointment_date`)
    REFERENCES `clinic_management`.`visits` (`patient_id` , `appointment_date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lab_test_results_code`
    FOREIGN KEY (`lab_test_code`)
    REFERENCES `clinic_management`.`lab_tests` (`lab_test_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinic_management`.`lab_tests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinic_management`.`lab_tests` ;

CREATE TABLE IF NOT EXISTS `clinic_management`.`lab_tests` (
  `lab_test_code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `reference_value` VARCHAR(45) NULL,
  PRIMARY KEY (`lab_test_code`),
  UNIQUE INDEX `lab_test_code_UNIQUE` (`lab_test_code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinic_management`.`nurses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinic_management`.`nurses` ;

CREATE TABLE IF NOT EXISTS `clinic_management`.`nurses` (
  `nurse_id` VARCHAR(25) NOT NULL,
  `personal_information_id` INT UNSIGNED NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`nurse_id`),
  INDEX `nurses_personal_information_id_idx` (`personal_information_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `nurse_id_UNIQUE` (`nurse_id` ASC),
  CONSTRAINT `nurses_personal_information_id`
    FOREIGN KEY (`personal_information_id`)
    REFERENCES `clinic_management`.`personal_information` (`personal_information_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinic_management`.`patients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinic_management`.`patients` ;

CREATE TABLE IF NOT EXISTS `clinic_management`.`patients` (
  `patient_id` VARCHAR(25) NOT NULL,
  `personal_information_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`patient_id`),
  INDEX `patients_personal_information_id_idx` (`personal_information_id` ASC),
  UNIQUE INDEX `patient_id_UNIQUE` (`patient_id` ASC),
  CONSTRAINT `patients_personal_information_id`
    FOREIGN KEY (`personal_information_id`)
    REFERENCES `clinic_management`.`personal_information` (`personal_information_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinic_management`.`personal_information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinic_management`.`personal_information` ;

CREATE TABLE IF NOT EXISTS `clinic_management`.`personal_information` (
  `personal_information_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `ssn` VARCHAR(9) NULL,
  `gender` VARCHAR(1) NULL,
  `street1` VARCHAR(45) NOT NULL,
  `street2` VARCHAR(45) NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `zip_code` VARCHAR(10) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`personal_information_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinic_management`.`visits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinic_management`.`visits` ;

CREATE TABLE IF NOT EXISTS `clinic_management`.`visits` (
  `patient_id` VARCHAR(25) NOT NULL,
  `appointment_date` DATETIME NOT NULL,
  `visit_date` DATETIME NOT NULL,
  `nurse_id` VARCHAR(25) NOT NULL,
  `weight` DECIMAL(5,2) NOT NULL,
  `systolic_blood_pressure` INT NOT NULL,
  `diastolic_blood_pressure` INT NOT NULL,
  `body_temperature` DECIMAL(5,2) NOT NULL,
  `pulse` INT NOT NULL,
  `symptoms` VARCHAR(500) NOT NULL,
  `initial_diagnosis` VARCHAR(200) NOT NULL,
  `final_diagnosis` VARCHAR(200) NULL,
  INDEX `visits_nurses_id_idx` (`nurse_id` ASC),
  PRIMARY KEY (`patient_id`, `appointment_date`),
  CONSTRAINT `visits_nurses_id`
    FOREIGN KEY (`nurse_id`)
    REFERENCES `clinic_management`.`nurses` (`nurse_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `visits_appointments_id`
    FOREIGN KEY (`patient_id` , `appointment_date`)
    REFERENCES `clinic_management`.`appointments` (`patient_id` , `date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
